FROM python:3.11-slim

# Installer les dépendances système
RUN apt-get update && apt-get install -y gcc

# Créer un dossier d'app
WORKDIR /app

# Copier le code
COPY main.py /app/main.py

# Installer les dépendances Python
RUN pip install --no-cache-dir fastapi uvicorn torch torchvision python-multipart

# Lancer l’API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
