FROM python:3.11-slim

WORKDIR /app

COPY front.py /app/front.py

# Installer les dépendances
RUN pip install --no-cache-dir streamlit streamlit-drawable-canvas requests Pillow

# Lancer l’app Streamlit
CMD ["streamlit", "run", "front.py", "--server.port=8501", "--server.address=0.0.0.0"]
